[package]
name = "tkn-watch"
version = "0.3.0"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
description = "watch tekton pipelinerun execution"
build = "build.rs"
keywords = ["kubernetes", "tekton", "pipelines"]

[dependencies]
kube = { version = "0.74.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.15.0", features = ["v1_23"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.44"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
askama = "0.11.1"
chrono = "0.4.19"
chrono-humanize = "0.2.1"
dialoguer = { version = "0.10.0", features = ["fuzzy-select"] }
clap = { version = "3.2", features = ["derive", "cargo"] }
regex = "1.5.5"
openssl = { version = "0.10.38", features = ["vendored"] }
spinner = "0.5.0"
goldie = "0.4.0"


[build-dependencies]
clap = { version = "3.2", features = ["cargo"] }
clap_complete = "3.1"
goldie = "0.4.0"
