[package]
name = "tkn-watch"
version = "0.1.0"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
description = "watch tekton pipelinerun execution"
build = "build.rs"

[dependencies]
kube = { version = "0.71.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.14.0", features = ["v1_23"] }
tokio = { version = "1.14.0", features = ["full"] }
anyhow = "1.0.44"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
askama = "0.11.1"
chrono = "0.4.19"
chrono-humanize = "0.2.1"
dialoguer = { version = "0.10.0", features = ["fuzzy-select"] }
clap = { version = "3.1", features = ["derive", "cargo"] }


[build-dependencies]
clap = { version = "3.1", features = ["cargo"] }
clap_complete = "3.1"
