[package]
name = "tkn-watch"
version = "0.3.0"
authors = ["Chmouel Boudjnah <chmouel@chmouel.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
description = "watch tekton pipelinerun execution"
build = "build.rs"
keywords = ["kubernetes", "tekton", "pipelines"]

[dependencies]
kube = { version = "0.74.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.16.0", features = ["v1_23"] }
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.65"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
askama = "0.11.1"
chrono = "0.4.22"
chrono-humanize = "0.2.2"
dialoguer = { version = "0.10.2", features = ["fuzzy-select"] }
clap = { version = "3.2", features = ["derive", "cargo"] }
regex = "1.5.5"
openssl = { version = "0.10.38", features = ["vendored"] }
spinner = "0.5.0"
goldie = "0.4.0"


[build-dependencies]
clap = { version = "3.2", features = ["cargo"] }
clap_complete = "3.2"
goldie = "0.4.0"
