# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknWatch < Formula
  desc "tkn-watch - watch tekton pipelinerun execution"
  homepage "https://github.com/chmouel/tkn-watch"
  version "0.1.0"

  on_macos do
    url "https://github.com/chmouel/tkn-watch/releases/download/0.1.0/tkn-watch_0.1.0_macOS_all.tar.gz"
    sha256 "bb5217689df8452a144be432570341be121ca7f18ba8236d975fed9a82f0de94"

    def install
      bin.install "tkn-watch" => "tkn-watch"
      prefix.install_metafiles
      bash_completion.install "completions/tkn-watch.bash"
      fish_completion.install "completions/tkn-watch.fish"
      zsh_completion.install "completions/_tkn-watch"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/tkn-watch/releases/download/0.1.0/tkn-watch_0.1.0_linux_amd64.tar.gz"
      sha256 "203963e91dfd4565a92e7be490737d18d1570e34b3dd295d2da438cc038537b4"

      def install
        bin.install "tkn-watch" => "tkn-watch"
        prefix.install_metafiles
        bash_completion.install "completions/tkn-watch.bash"
        fish_completion.install "completions/tkn-watch.fish"
        zsh_completion.install "completions/_tkn-watch"
      end
    end
  end
end
