# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TknWatch < Formula
  desc "tkn-watch - watch tekton pipelinerun execution"
  homepage "https://github.com/chmouel/tkn-watch"
  version "0.2.0"

  on_macos do
    url "https://github.com/chmouel/tkn-watch/releases/download/0.2.0/tkn-watch_0.2.0_macOS_all.tar.gz"
    sha256 "027b9b94bf6e2cdf9befc9e03e83ef971720f2fce34bb01c857a021e7a3e9125"

    def install
      bin.install "tkn-watch" => "tkn-watch"
      prefix.install_metafiles
      bash_completion.install "completions/tkn-watch.bash"
      fish_completion.install "completions/tkn-watch.fish"
      zsh_completion.install "completions/_tkn-watch"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/tkn-watch/releases/download/0.2.0/tkn-watch_0.2.0_linux_amd64.tar.gz"
      sha256 "5cc5035ff287015c8b75bacda0126956d2123d818fc9af7d41ffdab80c762eb7"

      def install
        bin.install "tkn-watch" => "tkn-watch"
        prefix.install_metafiles
        bash_completion.install "completions/tkn-watch.bash"
        fish_completion.install "completions/tkn-watch.fish"
        zsh_completion.install "completions/_tkn-watch"
      end
    end
  end
end
